# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from NewMusic import Music
import os,random
import eyed3 as E
import io
from PIL import Image


class Song:
    def __init__(self) -> None:
        pass

class Album:
    def __init__(self) -> None:
        pass
        
        

class Ui_MainWindow(object):
    def __init__(self) -> None:
        super(Ui_MainWindow,self).__init__()
        self.music = Music()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ## List widget for songs
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(575, 111, 431, 461))
        self.listWidget.setObjectName("listWidget")

        ## Widget for Footer
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 619, 1021, 161))
        self.widget.setObjectName("widget")

        ## Progress bar
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 991, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        ## Prev push buttton
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 100, 96, 36))
        self.pushButton.setObjectName("pushButton")

        ## Play / Pause  push button
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 100, 96, 36))
        self.pushButton_2.setObjectName("pushButton_2")

        ## Next Push button
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 100, 96, 36))
        self.pushButton_3.setObjectName("pushButton_3")

        ## Header Widget
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 0, 1011, 80))
        self.widget_2.setObjectName("widget_2")

        ## Album push button
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 10, 96, 36))
        self.pushButton_4.setObjectName("pushButton_4")

        ## Favourites push button
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 10, 96, 36))
        self.pushButton_5.setObjectName("pushButton_5")

        ## Songs push button
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 10, 96, 36))
        self.pushButton_6.setObjectName("pushButton_6")

        ## Label to add image
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 119, 431, 271))
        self.label.setObjectName("label")

        ## Label to add songs info
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 427, 431, 131))
        self.label_2.setObjectName("label_2")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.listWidget.addItems(self.music.songsList.keys())
        self.listWidget.itemSelectionChanged.connect(self.Select)
        self.pushButton_2.clicked.connect(self.music.pausePlay)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Prev"))
        self.pushButton_2.setText(_translate("MainWindow", "Play / Pause"))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.pushButton_4.setText(_translate("MainWindow", "Album"))
        self.pushButton_5.setText(_translate("MainWindow", "Favourits"))
        self.pushButton_6.setText(_translate("MainWindow", "Songs"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))

    def Select(self):
        self.music.selectSong(self.listWidget.currentItem().text())
        File = E.load(self.music.songsList[self.listWidget.currentItem().text()])
        print(File.tag.artist)
        self.pixmap = QtGui.QPixmap(File.tag.images)
        #self.pixmap = QtGui.QPixmap("Images/" + random.choice(os.listdir("Images/")))
        self.label.setPixmap(self.pixmap)
        self.label.resize(self.label.width(),self.label.height())
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
