# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Music

class Ui_MainWindow(object):
    def __init__(self) -> None:
        super(Ui_MainWindow,self).__init__()
        self.music = Music.Music()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(80, 470, 641, 13))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(89, 60, 601, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 560, 96, 36))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 560, 96, 36))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 560, 96, 36))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuAlbum = QtWidgets.QMenu(self.menubar)
        self.menuAlbum.setObjectName("menuAlbum")
        self.menuFavourites = QtWidgets.QMenu(self.menubar)
        self.menuFavourites.setObjectName("menuFavourites")
        self.menuPlaylist = QtWidgets.QMenu(self.menubar)
        self.menuPlaylist.setObjectName("menuPlaylist")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAlbum.menuAction())
        self.menubar.addAction(self.menuFavourites.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ######
        self.pushButton.clicked.connect(lambda : self.Play())
        pixmap = QtGui.QPixmap("/Images/Rohit_-Sharma-6.jpg")
        #label.setPixmap(pixmap)
        self.frame.setPixmap(pixmap)

    def Play(self):
        #print("Yes")
        self.music.selectSong()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Play/Pause"))
        self.pushButton_2.setText(_translate("MainWindow", "Prev"))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.menuAlbum.setTitle(_translate("MainWindow", "Album"))
        self.menuFavourites.setTitle(_translate("MainWindow", "Favourites"))
        self.menuPlaylist.setTitle(_translate("MainWindow", "Playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
