# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from NewMusic import Music


class Song_Menu(QtWidgets.QListWidget):
    def __init__(self) -> None:
        super(Song_Menu,self).__init__()


class Ui_MainWindow(object):
    def __init__(self) -> None:
        super(Ui_MainWindow,self).__init__()
        self.music = Music()
        self.Len = len(self.music.songsList)
        self.current = 0
        self.prev = -1
        self.next = 1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ## Progress Bar
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 520, 791, 13))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        ## Pushbutton(Prev)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 590, 96, 36))
        self.pushButton.setObjectName("pushButton")

        ## pushbutton_2(Play/ Pause)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 590, 96, 36))
        self.pushButton_2.setObjectName("pushButton_2")

        ## pushbutton_3(Next)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 590, 96, 36))
        self.pushButton_3.setObjectName("pushButton_3")

        ## Label for image
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 89, 591, 341))
        self.label.setObjectName("label")


        MainWindow.setCentralWidget(self.centralwidget)

        ## MenuBar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 28))
        self.menubar.setObjectName("menubar")
        #self.menubar.setCornerWidget(QtCore.center)

        ## MenuAlbum
        self.menuAlbum = QtWidgets.QMenu(self.menubar)
        self.menuAlbum.setObjectName("menuAlbum")

        ## Menu Favorites
        self.menuFavourites = QtWidgets.QMenu(self.menubar)
        self.menuFavourites.setObjectName("menuFavourites")

        ## Menu Playlist
        self.menuPlaylist = QtWidgets.QMenu(self.menubar)
        self.menuPlaylist.setObjectName("menuPlaylist")

        ## Menu All songs
        self.menuSongs = QtWidgets.QMenu(self.menubar)
        self.menuSongs.setObjectName("menuSongs")

        MainWindow.setMenuBar(self.menubar)

        ## statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        ## 
        self.menubar.addAction(self.menuAlbum.menuAction())
        self.menubar.addAction(self.menuFavourites.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())
        self.menubar.addAction(self.menuSongs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###############
        self.pushButton_2.clicked.connect(lambda : self.Play())
        self.pushButton.clicked.connect(lambda : self.Prev())
        self.pushButton_3.clicked.connect(lambda : self.Next())
        self.pixmap = QtGui.QPixmap("Images/Rohit-Sharma-6.jpg")
        self.label.setPixmap(self.pixmap)
        self.label.resize(self.label.width(),self.label.height())



    def Play(self):
        #print("Yes")
        self.music.selectSong(self.current)
        self.music.menu(1)

    def Next(self):
        #self.music.menu(6)
        self.prev += 1
        self.current += 1
        self.next += 1

        if(self.prev == self.Len):
            self.prev = 0
        elif(self.next == self.Len):
            self.next = 0
        elif(self.current == self.Len):
            self.current = 0

        self.music.selectSong(self.current)
        self.music.menu(1)
        """
        if(self.next == self.Len - 1):
            self.next = 0
        if(self.current == self.Len):
            self.current = 0
            self.prev = -1"""

    def Prev(self):
        #self.music.menu(6)
        self.prev -= 1
        self.current -=1 
        self.next -= 1

        if(self.prev == -(self.Len + 1)):
            self.prev = -1
        elif(self.current == -(self.Len + 1)):
            self.current = -1
        elif(self.next == -(self.Len + 1)):
            self.next = -1

        self.music.selectSong(self.current)
        self.music.menu(1)
        
        """
        if(self.prev == -(self.Len + 1)):
            self.prev = -1
        if()"""


    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Prev"))
        self.pushButton_2.setText(_translate("MainWindow", "Play/Pause"))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.progressBar.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        #self.label.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        #self.label.setSizePolicy(QtWidgets.QSizePolicy.expandingDirections)
        self.menuAlbum.setTitle(_translate("MainWindow", "Album"))
        self.menuFavourites.setTitle(_translate("MainWindow", "Favourites"))
        self.menuPlaylist.setTitle(_translate("MainWindow", "Playlist"))
        self.menuSongs.setTitle(_translate("MainWindow", "Songs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
